#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width		6
bspc config window_gap			0

bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_follows_pointer	true

bspc rule -a Wpg 		state=floating
bspc rule -a mpv 		state=floating
bspc rule -a Lxappearance 	state=floating
bspc rule -a Sxiv		state=floating
bspc rule -a Thunar		state=tiled

xset r rate 150 75 &
xset m 0 0 &
xset b off &
xsetroot -cursor_name left_ptr &
setxkbmap br
dunst &
$HOME/.config/wpg/wp_init.sh &
$HOME/.config/bspwm/bspwm_colors.sh &

startup_programs &
